# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  # This box is for serving internal data files to containers 
  # instead of hitting the internet each time a box or container is spun up
  
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "backend-web"

   config.vm.network "forwarded_port", guest: 80, host: 8080

   config.vm.provision "shell", inline: <<-SHELL     
     apt-get install -y apache2
	 ln -s /vagrant/tempdata /var/www/html
   SHELL
end
